name: Merge branch into 'main'

# Manual trigger only
on:
  workflow_dispatch:

jobs:
  do-merge:
    uses: contoroinc/common_github_workflows/.github/workflows/merge-into-branch.yaml@main
    with:
      target_branch: main
    secrets:
      private-deploy-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
